services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
  app:
    build: .
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./alembic
          target: /app/alembic
        - action: rebuild
          path: ./poetry.lock
    ports:
      - "8000:8000"
    environment:
      APP_CONFIG__DB__URL: mysql+aiomysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      APP_CONFIG__DB__ECHO: 0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data: