"""Add unique constaint for room.name and floor.id

Revision ID: 452bb3a84036
Revises: 531ff219b43a
Create Date: 2025-07-15 03:33:08.132572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "452bb3a84036"
down_revision: Union[str, Sequence[str], None] = "531ff219b43a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_rooms_floor_id_name"), "rooms", ["floor_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_rooms_floor_id_name"), "rooms", type_="unique")
    # ### end Alembic commands ###
