"""Add floors table

Revision ID: 2886c395c5dd
Revises: 16ec1e6e96d4
Create Date: 2025-07-13 14:15:06.442749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2886c395c5dd"
down_revision: Union[str, Sequence[str], None] = "16ec1e6e96d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("floor_number", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),

        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_floors_building_id_buildings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floors")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("floors")
    # ### end Alembic commands ###
