"""Add access_rules table

Revision ID: e53b9ca7fa3a
Revises: 78902fe70a46
Create Date: 2025-07-13 14:23:44.471635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e53b9ca7fa3a"
down_revision: Union[str, Sequence[str], None] = "78902fe70a46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_rules",        
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("time_from", sa.Time(), nullable=False),
        sa.Column("time_to", sa.Time(), nullable=False),

        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_access_rules_role_id_roles"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_access_rules_room_id_rooms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_rules")),
        sa.UniqueConstraint(
            "room_id", "role_id", name=op.f("uq_access_rules_room_id_role_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_rules")
    # ### end Alembic commands ###
