"""Add access_logs table

Revision ID: 8a3975cbcff5
Revises: 382463c743dc
Create Date: 2025-07-13 14:32:37.779497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a3975cbcff5"
down_revision: Union[str, Sequence[str], None] = "382463c743dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("enter", "exit", name="action_enum"),
            nullable=False,
        ),
        sa.Column(
            "access_allowed", sa.Boolean(), server_default="1", nullable=False
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_access_logs_room_id_rooms"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_access_logs_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_logs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_logs")
    # ### end Alembic commands ###
