"""Add rooms table

Revision ID: 846be5e1b4c0
Revises: 2886c395c5dd
Create Date: 2025-07-13 14:18:28.778241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "846be5e1b4c0"
down_revision: Union[str, Sequence[str], None] = "2886c395c5dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("floor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),

        sa.ForeignKeyConstraint(
            ["floor_id"], ["floors.id"], name=op.f("fk_rooms_floor_id_floors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
